/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.edu.view;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.edu.model.HoaDon;
import poly.edu.model.Lavie;
import poly.edu.model.SanPham;
import poly.edu.model.SanPham_1;
import poly.edu.repository.Auth;
import poly.edu.repository.ChuyenDoi;
import poly.edu.service.HoaDonRepository;
import poly.edu.service.SanPhamRepository;

/**
 *
 * @author Yen Nhi
 */
public class BanHang_Panel1 extends javax.swing.JPanel implements Runnable, ThreadFactory {

    private final SanPhamRepository spr = new SanPhamRepository();
    private final HoaDonRepository hdr = new HoaDonRepository();

    DefaultTableModel mol, molhd, molgh;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private static final long serialVersionUID = 6441489157408381878L;
    private final Executor executor = Executors.newSingleThreadExecutor();
    String qr = "";

    public BanHang_Panel1() {
        initComponents();
        initWebcam();
        mol = (DefaultTableModel) tblsanpham.getModel();
        molhd = (DefaultTableModel) tbldshd.getModel();
        molgh = (DefaultTableModel) tblgiohang.getModel();
        cboloctheloai.removeAllItems();
        cboloctheloai.addItem("S");
        cboloctheloai.addItem("M");
        cboloctheloai.addItem("L");
        cboloctheloai.addItem("XL");
        cboloctheloai.addItem("XXL");

        cbohttt.removeAllItems();
        cbohttt.addItem("Tiền mặt");
        cbohttt.addItem("Quẹt thẻ");
        cbohttt.addItem("Chuyển khoản");
//        tenNv.setText(Auth.user.getTenNV());
//        cbonv.addItem("Nguyễn Văn Long");
//        cbonv.addItem("Trần Hà Linh");
        loadDatatoTable();
        loadDatatoTableHD();
//        loadDatatoTableGH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtsdt = new javax.swing.JTextField();
        txtnamekh = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbltongdon = new javax.swing.JLabel();
        cbohttt = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        btnthanhToan = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        dateTao = new com.toedter.calendar.JDateChooser();
        tenNv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdotaiquay = new javax.swing.JRadioButton();
        rdogiaohang = new javax.swing.JRadioButton();
        btngiaohang = new javax.swing.JButton();
        btndagiao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtship = new javax.swing.JTextField();
        pnlwebcam = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldshd = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblgiohang = new javax.swing.JTable();
        btnxoasp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        cboloctheloai = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtfind = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("Sửa sản phẩm");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo Hóa Đơn"));

        jLabel3.setText("Tên KH");

        jLabel4.setText("Số ĐT");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setText("Tổng đơn hàng:");

        jLabel7.setText("Thanh toán");

        lbltongdon.setText("0");

        cbohttt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator9.setForeground(new java.awt.Color(102, 102, 102));

        jButton10.setText("Tạo HD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnthanhToan.setText("Thanh Toán");
        btnthanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhToanActionPerformed(evt);
            }
        });

        jLabel29.setText("Nhân Viên");

        jLabel30.setText("Ngày Tạo");

        dateTao.setDateFormatString("YYYY-MM-dd");

        tenNv.setText("Phạm Quang Thiện");

        jLabel1.setText("Địa Chỉ");

        jLabel2.setText("Hình Thức");

        buttonGroup1.add(rdotaiquay);
        rdotaiquay.setSelected(true);
        rdotaiquay.setText("Tại Quầy");
        rdotaiquay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdotaiquayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdogiaohang);
        rdogiaohang.setText("Giao Hàng");
        rdogiaohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdogiaohangActionPerformed(evt);
            }
        });

        btngiaohang.setText("Giao Hàng");
        btngiaohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaohangActionPerformed(evt);
            }
        });

        btndagiao.setText("Đã Giao Hàng");
        btndagiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndagiaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Phí Ship");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(txtnamekh)
                            .addComponent(txtsdt)))
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbohttt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltongdon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtship))
                    .addComponent(jSeparator9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btngiaohang))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btndagiao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnthanhToan)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rdotaiquay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdogiaohang))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tenNv, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamekh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdotaiquay)
                    .addComponent(rdogiaohang))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbltongdon))
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbohttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tenNv))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(dateTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(btngiaohang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndagiao)
                    .addComponent(btnthanhToan))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bán Hàng", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pnlwebcam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        pnlwebcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        tbldshd.setBackground(new java.awt.Color(242, 242, 242));
        tbldshd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Tên NV", "Khách Hàng", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tbldshd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldshdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldshd);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn Chi Tiết"));

        tblgiohang.setBackground(new java.awt.Color(242, 242, 242));
        tblgiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Giảm Giá", "Thành Tiền", "Trạng Thái"
            }
        ));
        tblgiohang.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tblgiohang);

        btnxoasp.setText("Xóa SP");
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });

        jButton1.setText("Làm Mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnxoasp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoasp)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        tblsanpham.setBackground(new java.awt.Color(242, 242, 242));
        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Thể Loại", "Chất Liệu", "Kích Thước", "Màu Sắc", "Số Lượng", "Đơn Giá"
            }
        ));
        tblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblsanpham);

        jLabel13.setText("Kích thước");

        cboloctheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboloctheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboloctheloaiActionPerformed(evt);
            }
        });

        jLabel14.setText("Tìm sản phẩm");

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        jButton2.setText("Làm mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboloctheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboloctheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnlwebcam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlwebcam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            addHD();
            molgh.setRowCount(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnthanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhToanActionPerformed
//        if (cbohttt.getSelectedIndex() == 1) {
//            txttienkhachdua.setText(lblcantt.getText().trim());
//            btnthanhToan.setEnabled(true);
//            lbltienthua.setText("0");
//        } else {
//            txttienkhachdua.setText("");
//            btnthanhToan.setEnabled(false);
//        }
        int index = tbldshd.getSelectedRow();
        int chon = JOptionPane.showConfirmDialog(this, "Hoan tat thanh toan?");
        if (chon != JOptionPane.YES_OPTION) {
            return;
        }
        int hds = tbldshd.getSelectedRow();
        int ma = Integer.parseInt(tbldshd.getValueAt(hds, 0).toString());
        if (hdr.deleteHD() != null) {
            JOptionPane.showMessageDialog(this, "Thanh toan thanh cong");
            loadDatatoTableHD();
            molgh.setRowCount(0);
        }
        if (index >= 0) {
            molhd.removeRow(index);

        }

    }//GEN-LAST:event_btnthanhToanActionPerformed

    private void tbldshdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldshdMouseClicked
        //        int index = tbldshd.getSelectedRow();
        //        if(index >= 0){
        //            tblgiohang.setRow
        //        }
    }//GEN-LAST:event_tbldshdMouseClicked

    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        try {
            xoaSP();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnxoaspActionPerformed

    private void tblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsanphamMouseClicked
        int row = tbldshd.getSelectedRow();
        if (row == (-1)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc tạo hóa đơn");
            return;
        }
        int rowsp = tblsanpham.getSelectedRow();
        String inp = JOptionPane.showInputDialog("Nhập số lượng");
        if (inp == null) {
            return;
        }
        if (!inp.trim().matches("^\\d+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            return;
        }
        int slm = Integer.parseInt(inp);
        int selectidsp = tblsanpham.getSelectedRow();
        String masp = tblsanpham.getValueAt(selectidsp, 0).toString();
        boolean isNotExisted = true;
        for (Lavie s : spr.getAllSP()) {
            if (masp.equals(s.getMaSP())) {
                s.setSoLuong(s.getSoLuong() - slm);
                loadDatatoTable();
                isNotExisted = false;
                break;
            }
        }
        List<Lavie> listTong = new ArrayList<>();
        listTong = spr.getAllSP();
        HoaDonRepository.loadDatatoGH(tblgiohang, listTong.get(rowsp), inp);
        lbltongdon.setText(HoaDonRepository.taiQuay(tblgiohang));
//        double tienship, tongdon, cantt;
//        tienship = Double.parseDouble(txtship.getText());
//        tongdon = Double.parseDouble(lbltongdon.getText());
//        cantt = tienship + tongdon;

//        try {
//            int index = tblsanpham.getSelectedRow();
//            int ind = tblgiohang.getSelectedRow();
//            int in = Integer.parseInt(tblsanpham.getValueAt(index, 6).toString());
//            int inds = Integer.parseInt(tblgiohang.getValueAt(ind, 2).toString());
////            inp = tblgiohang.getValueAt(index, 2).toString();
//            tblsanpham.setValueAt(in - inds, index, 6);
////            double tt = Double.parseDouble(inp) * Double.parseDouble(tblgiohang.getValueAt(index, 3).toString());
////            tblgiohang.setValueAt(tt, index, 5);
//            loadDatatoTable();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        try {
//            int index = tblsanpham.getSelectedRow();
//            int ind = tblgiohang.getSelectedRow();
//            int in = Integer.parseInt(tblsanpham.getValueAt(index, 6).toString());
//            int inds = Integer.parseInt(tblgiohang.getValueAt(ind, 2).toString());
//            int slm = in-inds;
//            
//            if (spr.update(sp, slm, masp)) {
//
//            }
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_tblsanphamMouseClicked

    private void cboloctheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboloctheloaiActionPerformed
        try {
            logDG();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboloctheloaiActionPerformed

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        mol.setRowCount(0);
        String tim = txtfind.getText();

        for (Lavie s : spr.selectbytheLoai(tim)) {
            mol.addRow(new Object[]{
                s.getMaSP(),
                s.getTenSP(),
                s.getTheLoai(),
                s.getChatLieu(),
                s.getKichThuoc(),
                s.getMauSac(),
                s.getSoLuong(),
                s.getDonGia()});
        }
    }//GEN-LAST:event_txtfindKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            int index = tblgiohang.getSelectedRow();
            String inp = JOptionPane.showInputDialog("Nhập số lượng");
//            inp = tblgiohang.getValueAt(index, 2).toString();
            tblgiohang.setValueAt(inp, index, 2);
            double tt = Double.parseDouble(inp) * Double.parseDouble(tblgiohang.getValueAt(index, 3).toString());
            tblgiohang.setValueAt(tt, index, 5);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rdotaiquayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdotaiquayActionPerformed
        try {
            if (rdotaiquay.isSelected()) {
                txtnamekh.setEnabled(false);
                txtsdt.setEnabled(false);
                txtdiachi.setEnabled(false);
                txtship.setEnabled(false);
                btngiaohang.setEnabled(false);
                btndagiao.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rdotaiquayActionPerformed

    private void rdogiaohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdogiaohangActionPerformed
        try {
            if (rdogiaohang.isSelected()) {
                txtnamekh.setEnabled(true);
                txtsdt.setEnabled(true);
                txtdiachi.setEnabled(true);
                txtship.setEnabled(true);
                btngiaohang.setEnabled(true);
                btndagiao.setEnabled(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rdogiaohangActionPerformed

    private void btngiaohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaohangActionPerformed
        try {
            int row = tbldshd.getSelectedRow();
            if (row == (-1)) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc tạo hóa đơn");
                return;
            }
            String tenkh, sdt, diachi, phiship;
            tenkh = txtnamekh.getText();
            sdt = txtsdt.getText();
            diachi = txtdiachi.getText();
            phiship = txtship.getText();
            if (tenkh.equals("") || sdt.equals("") || diachi.equals("") || phiship.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin cần thiết để giao hàng.");
                return;
            }
            try {
                double phiShip = Double.parseDouble(txtship.getText());
                if (phiShip < 0) {
                    JOptionPane.showMessageDialog(this, "Phí giao hàng phải lớn hơn 0.");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn giao hàng?");
            if (chon != JOptionPane.YES_OPTION) {
                return;
            }
            int index = tbldshd.getSelectedRow();
            tbldshd.setValueAt("Chờ giao hàng", index, 4);
            txtdiachi.setText("");
            txtnamekh.setText("");
            txtsdt.setText("");
            lbltongdon.setText("");
            dateTao.setDate(null);
            txtship.setText("");
            molgh.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Lấy đơn hàng thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btngiaohangActionPerformed

    private void btndagiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndagiaoActionPerformed
        int index = tbldshd.getSelectedRow();
        int chon = JOptionPane.showConfirmDialog(this, "Xác nhận đã giao hàng?");
        if (chon != JOptionPane.YES_OPTION) {
            return;
        }
        if (hdr.deleteHD() != null) {
            JOptionPane.showMessageDialog(this, "Giao hàng thành công");
            loadDatatoTableHD();
            molgh.setRowCount(0);
        }

    }//GEN-LAST:event_btndagiaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn làm mới toàn bộ??");
            if (chon != JOptionPane.YES_OPTION) {
                return;
            }
            molgh.setRowCount(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            loadDatatoTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndagiao;
    private javax.swing.JButton btngiaohang;
    private javax.swing.JButton btnthanhToan;
    private javax.swing.JButton btnxoasp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbohttt;
    private javax.swing.JComboBox<String> cboloctheloai;
    private com.toedter.calendar.JDateChooser dateTao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbltongdon;
    private javax.swing.JPanel pnlwebcam;
    private javax.swing.JRadioButton rdogiaohang;
    private javax.swing.JRadioButton rdotaiquay;
    private javax.swing.JTable tbldshd;
    private javax.swing.JTable tblgiohang;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JLabel tenNv;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtnamekh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtship;
    // End of variables declaration//GEN-END:variables

    private void loadDatatoTable() {
        mol.setRowCount(0);
        ArrayList<Lavie> lst = spr.getAllSP();
        for (Lavie s : lst) {
            mol.addRow(new Object[]{
                s.getMaSP(),
                s.getTenSP(),
                s.getTheLoai(),
                s.getChatLieu(),
                s.getKichThuoc(),
                s.getMauSac(),
                s.getSoLuong(),
                s.getDonGia()});
        }
    }

    private void loadDatatoTableHD() {
        molhd.setRowCount(0);
        ArrayList<HoaDon> lst = hdr.getAllHD();
        for (HoaDon h : lst) {
            molhd.addRow(new Object[]{
                h.getMaHD(),
                h.getTenNV(),
                h.getTenKH(),
                h.getNgayTao(),
                h.getTrangThai()
            });
        }
    }

    private HoaDon readForm() throws Exception {
        HoaDon hd = new HoaDon();
        hd.setTenNV(tenNv.getText());
        hd.setTenKH(txtnamekh.getText());
        Date da = dateTao.getDate();
        String date = sdf.format(da);
        hd.setNgayTao(sdf.parse(date));
//        hd.setNgayTao("2023");
        hd.setTrangThai("Chưa thanh toán");
        return hd;
    }

    private void addHD() throws Exception {
        try {
            if (dateTao.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn ngày tạo hóa đơn");
                dateTao.requestFocus();
                return;
            }
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tạo hóa đơn mới?");
            if (chon != JOptionPane.YES_OPTION) {
                return;
            }
            HoaDon hdd = readForm();
            if (hdr.addHD(hdd) != null) {
                JOptionPane.showMessageDialog(this, "Tạo thành công");
                loadDatatoTableHD();
            } else {
                JOptionPane.showMessageDialog(this, "Tạo thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tạo");
            e.printStackTrace();
        }
    }

    private void xoaSP() {
        try {
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa sản phẩm?");
            if (chon != JOptionPane.YES_OPTION) {
                return;
            }
            int index = tblgiohang.getSelectedRow();
            if (index >= 0) {
                molgh.removeRow(index);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                for (int i = 0; i < tblgiohang.getRowCount(); i++) {
                    tblgiohang.setValueAt(i + 1, i, 0);
                }
            }
            lbltongdon.setText(HoaDonRepository.taiQuay(tblgiohang));
        } catch (Exception e) {
        }
    }

    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); // 0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        pnlwebcam.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 120));//set view webcam
        executor.execute(this);
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException ex) {
                Logger.getLogger(BanHang_Panel1.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (result != null) {
                int row = tbldshd.getSelectedRow();
                if (row == (-1)) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc tạo hóa đơn");
                    return;
                }
//                int rowsp = tblsanpham.getSelectedRow();
                String inp = JOptionPane.showInputDialog("Nhập số lượng");
                if (inp == null) {
                    return;
                }

                if (!inp.trim().matches("^\\d+")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
                    return;
                }
                qr = result.getText();
                Lavie sp = SanPhamRepository.getSP(qr);
                HoaDonRepository.loadDatatoGH(tblgiohang, sp, inp);
                lbltongdon.setText(HoaDonRepository.taiQuay(tblgiohang));
            }
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }

    private void logDG() {
        String loc = cboloctheloai.getSelectedItem().toString();
        mol.setRowCount(0);
        for (Lavie s : spr.selectbyKT(loc)) {
            mol.addRow(new Object[]{
                s.getMaSP(),
                s.getTenSP(),
                s.getTheLoai(),
                s.getChatLieu(),
                s.getKichThuoc(),
                s.getMauSac(),
                s.getSoLuong(),
                s.getDonGia()});
        }
    }

}
