/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.edu.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.edu.model.DotGiamGia;
import poly.edu.model.DotGiamGiaTheoKH;
import poly.edu.model.DotGiamGiaTheoSP;
import poly.edu.service.DotGiamGiaDAO;


/**
 *
 * @author ADMIN
 */
public class DotGiamGia1 extends javax.swing.JPanel {

    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel model = new DefaultTableModel();
    private final DotGiamGiaDAO dao = new DotGiamGiaDAO();
    
    public DotGiamGia1() {
        initComponents();
        //setLocationRelativeTo(null);
        model = (DefaultTableModel) tbl_dgg.getModel();
        loadDataTable();
        if (tbl_dgg.getRowCount() > 0) {
            tbl_dgg.setRowSelectionInterval(0, 0);
            showDetail();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_tim = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_tenSP = new javax.swing.JTextField();
        txt_tenKH = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_gtgg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nbd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nkt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_dkgg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_mota = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dgg = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đợt Giảm Giá"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm đợt giảm giá"));

        btn_tim.setText("Tìm kiếm ");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_tim)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setText("ID_DGG");

        jLabel2.setText("TenSP");

        jLabel3.setText("TenKH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id)
                            .addComponent(txt_tenSP)
                            .addComponent(txt_tenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Đợt Giảm Giá Chi Tiết"));

        jLabel4.setText("TenDGG");

        jLabel5.setText("GiaTriGG");

        jLabel6.setText("NgayBatDau");

        jLabel7.setText("NgayKetThuc");

        jLabel8.setText("DieuKienGiamGia");

        jLabel9.setText("MoTa");

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ten)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gtgg)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btn_clear))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update))))
                    .addComponent(txt_nbd)
                    .addComponent(txt_nkt)
                    .addComponent(txt_dkgg)
                    .addComponent(txt_mota))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txt_gtgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_nbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_nkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txt_dkgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txt_mota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_dgg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_DGG", "TenSP", "TenKH", "TenDGG", "GiaTriGG", "NgayBatDau", "NgayKetThuc", "DieuKienGiamGia", "MoTa"
            }
        ));
        tbl_dgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dggMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dgg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            update();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tbl_dggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dggMouseClicked
        try {
            showDetail();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tbl_dggMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            add();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            delete();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try {
            clear();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        model = (DefaultTableModel) tbl_dgg.getModel();
        model.setRowCount(0);
        int ID_DGG = Integer.parseInt(txt_tim.getText());
        for (DotGiamGia dgg : dao.getID_DGG(ID_DGG)) {
            model.addRow(new Object[]{
                dgg.getID_DGG(),
                dgg.getTenSP(),
                dgg.getTenKH(),
                dgg.getTenDGG(),
                dgg.getNgayBatDau(),
                dgg.getNgayKetThuc(),
                dgg.getLoaiGiamGia(),
                dgg.getGiaTriGG(),
                dgg.getDieuKienGiamGia(),
                dgg.getMoTa()
            });
        }     
    }//GEN-LAST:event_btn_timActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dgg;
    private javax.swing.JTextField txt_dkgg;
    private javax.swing.JTextField txt_gtgg;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_nbd;
    private javax.swing.JTextField txt_nkt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tenKH;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables

    

    private void loadDataTable() {
        model.setRowCount(0);
        ArrayList<DotGiamGia> listdgg = dao.getAllDotGiamGia();
        for (DotGiamGia dgg : listdgg) {
            model.addRow(new Object[]{
                dgg.getID_DGG(),
                dgg.getTenSP(),
                dgg.getTenKH(),
                dgg.getTenDGG(),
                dgg.getNgayBatDau(),
                dgg.getNgayKetThuc(),
                dgg.getGiaTriGG(),
                dgg.getDieuKienGiamGia(),
                dgg.getMoTa()
            });
        }
    }

    private void showDetail() {
        int index = tbl_dgg.getSelectedRow();
        txt_id.setText(tbl_dgg.getValueAt(index, 0).toString());
        txt_tenSP.setText(tbl_dgg.getValueAt(index, 1).toString());
        txt_tenKH.setText(tbl_dgg.getValueAt(index, 2).toString());
        txt_ten.setText(tbl_dgg.getValueAt(index, 3).toString());
        txt_nbd.setText(tbl_dgg.getValueAt(index, 4).toString());
        txt_nkt.setText(tbl_dgg.getValueAt(index, 5).toString());
        txt_gtgg.setText(tbl_dgg.getValueAt(index, 6).toString());
        txt_dkgg.setText(tbl_dgg.getValueAt(index, 7).toString());
        txt_mota.setText(tbl_dgg.getValueAt(index, 8).toString());
    }

    private void add() throws ParseException {
        DotGiamGia dgg = getForm();
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            if (dao.add(dgg) != null) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");                
            }
        } catch (Exception e) {
        }
    }
    
    private void delete() throws ParseException {
        DotGiamGia dgg = getForm();
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            int index = tbl_dgg.getSelectedRow();
            int maDGG = Integer.parseInt(txt_id.getText());
            if (dao.delete(index, maDGG) != null) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");                
            }
        } catch (Exception e) {
        }
    }
    
    private void update() throws ParseException {
        DotGiamGia dgg = getForm();
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có cập nhật thêm?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            int index = tbl_dgg.getSelectedRow();
            if (dao.update(dgg) != null && index >= 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, " thất bại");                
            }
        } catch (Exception e) {
        }
    }
    
    private DotGiamGia getForm() throws ParseException {
        DotGiamGia dgg = new DotGiamGia();
        dgg.setID_DGG(Integer.parseInt(txt_id.getText()));
        DotGiamGiaTheoSP sp = new DotGiamGiaTheoSP();
        dgg.setTenSP(sp);
        DotGiamGiaTheoKH kh = new DotGiamGiaTheoKH();
        dgg.setTenKH(kh);
        dgg.setTenDGG(txt_ten.getText());
        dgg.setNgayBatDau(format.parse(txt_nbd.getText()));
        dgg.setNgayKetThuc(format.parse(txt_nkt.getText()));
        dgg.setGiaTriGG(txt_gtgg.getText());
        dgg.setDieuKienGiamGia(txt_dkgg.getText());
        dgg.setMoTa(txt_mota.getText());
        
        return dgg;
    }

    private void clear() {
         txt_dkgg.setText("");
         txt_gtgg.setText("");
         txt_tenKH.setText("");
         txt_tenSP.setText("");
         txt_mota.setText("");
         txt_nbd.setText("");
         txt_nkt.setText("");
         txt_ten.setText("");
    }

    
    
}
